<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
		<OutputType>WinExe</OutputType>
		<RootNamespace>PvPmo</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ApplicationTitle>PvPmo</ApplicationTitle>
		<ApplicationId>com.companyname.pvpmo</ApplicationId>
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>
		<WindowsPackageType>None</WindowsPackageType>
		<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>

		<MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation>

		<!-- EXE stand-alone -->
		<RuntimeIdentifier>win10-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<!-- Configurazioni personalizzate -->
	<PropertyGroup>
		<Configurations>Debug;Release;DEV;PROD</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<DefineConstants>DEBUG;DEV</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DefineConstants>RELEASE;PROD</DefineConstants>
	</PropertyGroup>

	<!-- File JSON nella cartella Data -->
	<ItemGroup>
		<EmbeddedResource Include="Data\*.json" />
	</ItemGroup>

	<!-- Icone e splash -->
	<ItemGroup>
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />
	</ItemGroup>

	<!-- Immagini -->
	<ItemGroup>
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
	</ItemGroup>

	<!-- Font -->
	<ItemGroup>
		<MauiFont Include="Resources\Fonts\*" />
	</ItemGroup>

	<!-- Asset grezzi -->
	<ItemGroup>
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="Resources\Config\**" />
		<EmbeddedResource Remove="Resources\Config\**" />
		<MauiCss Remove="Resources\Config\**" />
		<MauiXaml Remove="Resources\Config\**" />
		<None Remove="Resources\Config\**" />
	</ItemGroup>

	<!-- Dipendenze NuGet -->
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="12.0.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.5" />
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="9.0.5" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.5" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.81" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.6" />
		<PackageReference Include="MySqlConnector" Version="2.4.0" />
		<PackageReference Include="System.Data.OleDb" Version="9.0.6" />
	</ItemGroup>

	<!-- XAML -->
	<ItemGroup>		
		<MauiXaml Update="Resources\Templates\FinalizzaTemplate.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>		
		<MauiXaml Update="Resources\Templates\NormalizzaTemplate.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>		
		<MauiXaml Update="Resources\Templates\OrigineTemplate.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>		
		<MauiXaml Update="Resources\Templates\ProgressTemplate.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>		
		<MauiXaml Update="Resources\Templates\UtenteTemplate.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>		
		<MauiXaml Update="View\GesAcsView.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>		
		<MauiXaml Update="View\JsonEditorView.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>		
		<MauiXaml Update="View\LoginView.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="View\ModDataView.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	</ItemGroup>

	<!-- Cartelle -->
	<ItemGroup>
		<Folder Include="Archivio\Setup\" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="View\GesAcsView.xaml.cs">
			<DependentUpon>GesAcsView.xaml</DependentUpon>
		</Compile>		
		<Compile Update="View\MainPageView.xaml.cs">
			<DependentUpon>MainPageView.xaml</DependentUpon>
		</Compile>
		<Compile Update="View\ModDataView.xaml.cs">
			<DependentUpon>ModDataView.xaml</DependentUpon>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<PRIResource Remove="Resources\Config\**" />
	</ItemGroup>

</Project>
